version: '3.8'

services:
  # --- Spring Boot Backend ---
#  app:
#    container_name: iflow-tracksys-proxy
#    build:
#      context: . # Spring projesinin olduğu klasör
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tracksys?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#      - SPRING_DATASOURCE_PASSWORD=1234
#    depends_on:
#      db:
#        condition: service_healthy
#    networks:
#      - tracksys-network

  # --- MySQL Database ---
  db:
    image: mysql:8.0
    container_name: tracksys-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tracksys
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tracksys-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

#  # --- React Frontend ---
#  frontend:
#    container_name: tracksys-frontend
#    build:
#      context: ../Tracksys-FE/tracksys-app # React projesinin olduğu klasör (adını kendine göre düzelt)
#      dockerfile: Dockerfile
#    ports:
#      - "5173:80" # Nginx 80'de çalışır, biz dışarıya 5173 veriyoruz
#    depends_on:
#      - app
#    networks:
#      - tracksys-network

volumes:
  mysql_data:

networks:
  tracksys-network:
    driver: bridge