spring.application.name=iflow-tracksys-proxy
miles.baseUrl=https://mws.hedeffilotest.com:4443
miles.username = TRACKSYS
miles.password =ws7139!!


# Tek dosya boyutu limiti
spring.servlet.multipart.max-file-size=30MB

# Tüm request boyutu limiti
spring.servlet.multipart.max-request-size=30MB

# Opsiyonel: Tomcat max swallow size (embedded tomcat kullan?yorsan)
server.tomcat.max-swallow-size=30MB